# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Funcoder Developer Blog
email: funcoder@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My place to write about all things coding and technology. From learning
  new languages and frameworks, science and technology that interests me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://funcoder.com" # the base hostname & protocol for your site
twitter_username: funcoder
github_username:  funcoder
permalink: pretty
# Build settings
markdown: kramdown
kramdown:
  input: GFM
